### ISSUE TITLE
unexpected output with flank

### ISSUE THREAD

**Issue by crawld** [teamholtz/DripTorch#70]
i'm encountering several issues when using flank. it's possible i'm using the api wrong.

first, i always get n - 1 igniters in the output pattern. is this expected?

![image](https://user-images.githubusercontent.com/7037909/192354065-b5acece7-4081-4ef7-bde8-5578bd6bf6fb.png)

second, setting igniters to 4 gives an exception:

` File "/igniter/./app/app.py", line 56, in create
    pattern = dt.firing.Flank(firing_area, crew).generate_pattern()
  File "/usr/local/lib/python3.10/site-packages/driptorch/firing/flank.py", line 36, in generate_pattern
    return self._generate_pattern()
  File "/usr/local/lib/python3.10/site-packages/driptorch/firing/_base.py", line 54, in _generate_pattern
    timed_paths = propagator.forward(init_paths, self._ignition_crew)
  File "/usr/local/lib/python3.10/site-packages/driptorch/pattern.py", line 266, in forward
    self._init_path_time(self.spacing)
  File "/usr/local/lib/python3.10/site-packages/driptorch/pattern.py", line 353, in _init_path_time
    path.start_time = prev_start_time + self._get_offset(
  File "/usr/local/lib/python3.10/site-packages/driptorch/pattern.py", line 393, in _get_offset
    cur_igniter.geometry.iloc[0].coords[0])
  File "/usr/local/lib/python3.10/site-packages/shapely/coords.py", line 85, in __getitem__
    raise IndexError("index out of range")
`

also, for higher numbers of igniters, the pattern stops before they all reach the boundary:

![image](https://user-images.githubusercontent.com/7037909/192354634-d6da0530-bce3-431f-846b-4a12dbeccf59.png)

**Comment by lucaswells** [comment]
Hi @crawld. These are all bugs. I'll work on a new release. Can you post the GeoJSON for that unit as a comment here?

**Comment by crawld** [comment]
Thanks, Lucas. attaching the geojson.

[inspiration.geojson.zip](https://github.com/teamholtz/DripTorch/files/9649414/inspiration.geojson.zip)

**Comment by lucaswells** [comment]
The first issue is an easy fix, but I can't reproduce the second or third issue you mentioned. Can you provide the rate argument you used for the dash igniter?

Here's a screenshot of the 20 igniters going all the way to the boundary. Do you think the third issue could be a mapbox rendering issue?

![image](https://user-images.githubusercontent.com/12506947/192374256-417b1f5a-dd56-4327-8bd8-b1c98e044a19.png)

**Comment by crawld** [comment]
the IndexError happens at rate -0.2 (dashes), rate 0 (lines), rate 0.1 (dots). it's possible third issue is rendering.

**Comment by crawld** [comment]
did the flanking pattern change since 0.4.0? here's what 3 igniters looks like in 0.4.0:

![image](https://user-images.githubusercontent.com/7037909/192383330-6fb8a659-cc4b-41c8-9f03-51293fef2632.png)

here's what it looks like in 0.5.1:

![image](https://user-images.githubusercontent.com/7037909/192383662-6b5140bf-4f37-4720-923e-092f775313bd.png)

**Comment by lucaswells** [comment]
I couldn't replicate the index error with the spatial data and igniter configuration you provided. I will release a new version with the 1 off fix though.

The differences you're seeing in the flank technique between v0.4 and v0.5 is related to issue #60. I think it's common for a single heat pass over the unit when flanking, but I'll add an argument to control multi-heat flank patterns in the next release.

**Comment by lucaswells** [comment]
@crawld and @drosales95, there are a few changes to the flank technique. First, if you don't provide a `depth` argument then the depth is compute to space a single heat of igniters across the unit. If you provide a depth parameter, then you'll see multiple heats like you did in v0.4. Second, and this applies to both flank and strip techniques, you can provide a `heat_depth` argument to space out the heats. This should help keep igniters from walking through fire set in the previous heat. Lastly, the time it takes for igniters to traverse back to the opposite side of the unit after a flanking heat is incorporated in the time propagation.

**Comment by crawld** [comment]
awesome, thanks Lucas!
