### ISSUE TITLE
Implement inferno firing technique

### ISSUE THREAD

**Issue by lucaswells** [teamholtz/DripTorch#73]
This firing technique will ignite every cell in the unit. :fire: :fire: :fire:

**Comment by drosales95** [comment]
I was about to come post about this... Beat me to it.

**Comment by lucaswells** [comment]
@drosales95, can you test the inferno technique in QF? I used format 5 and set the start/end times to (0,0), but you can use the time offset in the exporter to bump them up. Honestly, I have no idea if it will work, so let me know what happens!
